title: ">dr.kb< multiverse"
description: "grab a bowl ... 🌿🍯🔥💨"
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

# Custom CSS override
remote_theme: jekyll-theme-hacker
sass:
  style: compressed
