title: >dr.kb< multiverse  
description: grab a bowl ... 🌿🍯🔥💨
show_downloads: true
google_analytics:

# No theme - full custom control
theme: null

# Your custom settings
vibe: "ethical"
collaborator: "#KotV"
baseurl: ""
url: "https://bkornpob.github.io"
